package com.meyratech.vicenze.backend.model;

import java.util.Arrays;
import java.util.List;

/**
 * ekocbiyik on 31.08.2019
 */
public class ItemDetailUtils {

    public static List<String> eventTypeList = Arrays.asList("IN", "INV_IN", "EXP", "OUT");
    public static List<String> mainItemList = Arrays.asList("UNASSIGNED", "LOAN", "PLOT", "CONSTRUCTION", "OFFICIAL SET UP", "GENERAL EXPENSES", "FIXTURE", "SALES", "CP", "INTERBOOK", "SALES & MARKETING");
    public static List<String> bookList = Arrays.asList("MSM", "ALPHA", "BTRL BA", "VB-SH", "BRD-S BV", "BRD-SH", "NKASA-I", "NBG", "INVENTORY", "BP-BA", "NKASA-A", "VB-S BV", "EB");
    public static List<String> transactionList = Arrays.asList(
            "DEMOLUTION", "SALES CONTRACT", "TRANSFER TAX", "VAT", "ACC. SERVICES", "TAX", "COURRIER FEE", "CHEMICAL TOILET", "PAYBACK",
            "REAL ESTATE AGENCY FEE", "ARCHEO. DIGGING", "PLOT REPAYMENT", "WITHHOLDING TAX", "SALARY", "STEEL", "FAULT FRAMES", "WHEELIE BIN",
            "BRICKS", "PLOT PURCHASE", "GRATUS PM", "MISC.", "SALES & MARKETING", "INSPECTION", "LICENCE FEES", "INCORPORATION SERVICES", "ENERGY",
            "BUSINESS DEV.", "LOAN TRANSFER", "NOTARY", "LEGAL SERVICES", "MAINTENANCE", "PLOT PAYMENT", "BANKING FEES", "ELECTRICAL WORKS", "INSULATION",
            "POOL", "UTILITY", "MATERIALS", "COMMUNICATION", "STATIONARY", "CRANE", "GEOLOGICAL STUDY", "CLEANING", "VEHICLE EXPENSES", "ENGINEER",
            "PLUMBING", "SUPERVISION SERVICES", "PUMP", "PROPERTY TAX", "PLASTER", "MEMBERSHIP&OFFICIAL FEES", "FENCE & INSTALLATION", "BRICK WORKS",
            "ELECTRICAL&PLUMBING", "EQUIPMENT", "ARCH. SERVICES", "TRANSPORT", "GUARANTEE LETTER", "LAWYER FEE", "TOPOGRAFIC PLAN", "IKA", "STEEL CONTRACTOR",
            "CONCRETE CONTRACTOR", "EXCAVATION", "MANAGEMENT", "CHAMBERS", "TRANSFER FEE", "GOVERNANCE", "EXTRA SERVICES", "LEGAL EXPENSES", "DEMOLITION PERMIT",
            "CUSTOMER PAYMENT", "CONTRACTOR", "PLASTER WORKS", "MOTOR VEHICLE", "CONCRETE", "CONSULTANCY", "RENOVATION", "MUNICIPALITY", "COMMISSION",
            "OKEANIDON 3", "OTHERS", "SCAFFOLDERS", "SAFETY/GENERAL EXPENSES", "TOPOGRAPHER", "LEASE", "ARCHEO. INSP.", "BUILDING MATTERIALS", "DAILY WORKERS");

}
